#!/usr/bin/env bash
# Bash script that will display information about subdomains.
domainName=$1

function displayInformation {
    local subDomains=("$@")

    for sub_domain in "${subDomains[@]}"; do
        result=$(dig "$sub_domain.$domainName" | grep -A1 'ANSWER SECTION:' | awk '{print $4, $5}')
        recordType=$(echo "$result" | awk '{print $1}' | tr -d '\n')
        IP=$(echo "$result" | awk '{print $2}' | tr -d '\n')
        echo "The subdomain $sub_domain is a $recordType record and points to $IP"
    done
}


if [ $# -eq 1 ];then
    displayInformation "www" "lb-01" "web-01" "web-02";
fi

if [ $# -eq 2 ];then
    displayInformation "$2";
fi